[package]
name = "mermer-rs"
version = "0.1.0"
authors = ["Jakob L. Kreuze <zerodaysfordays@sdf.lonestar.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
